### ISSUE TITLE
[Feat]: Implement Generating Randomized Schedules

### ISSUE THREAD

**Issue by lilianaconstantino** [BizzNEST/salinas-bizznest-scheduler#18]
**Description**
The application should randomly generate a schedule that pairs or groups interns according to specified rules.
Pairing rules should include:

-Different city pairing: Interns are paired with others from different cities.
-Different department pairing: Interns are paired with others from different departments.

Users should be able to turn these rules on or off depending on their requirements.

**Tasks** 

- [x] #28
- [x] #30
- [x] #29

**Comment by AlonCS** [comment]
I can take care of this

**Comment by elimanzo** [comment]
> I can take care of this 

Awesome, for this project I want everyone to have experience with all aspects of this project. 

We'll have everyone work on a piece of the algorithm (that's why there's 3 sub task 😀 )

**Comment by AlonCS** [comment]
Sounds good.
