### ISSUE TITLE
[Feat]: Display Intern data

### ISSUE THREAD

**Issue by jacky-p** [BizzNEST/salinas-bizznest-scheduler#19]
## Description
After Creating the `intern.json` display all the interns dynamically 

### Tasks

- [ ] Figure out a way to parse the json data
- [ ] display it dynamically (hint: how can we iterate through an object?) - we can display it through the console for this task

### Additional Resources + Notes
[JSON](https://www.w3schools.com/js/js_json.asp)

**Comment by elimanzo** [comment]
Closing because of #43
